aws:
  region: us-east-1
  accessKey: __ENTER_ACCESS_KEY__
  secretKey: __ENTER_SECRET_KEY__

backend:
  image: 
    repository: brandonodiwuor/todo-backend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2

frontend:
  image: 
    repository: brandonodiwuor/todo-frontend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1

nginx:
  image: 
    repository: brandonodiwuor/todo-reverseproxy
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1